-- Add SUGGESTION_RECEIVED and USER_MENTIONED to NotificationType
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUGGESTION_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'USER_MENTIONED';
